env:
  TARGET_ECS_SERVICE: jwt-authentication

steps:
  - name: ":node: Run Tests"
    command: "/etc/buildkite-agent/buildkite-scripts/ecs-npm-multistage-docker-build.sh -b"

  - wait: ~

  - block: "Publish branch to GitHub registry"
    branches: "!master"

  - name: "Publish to GitHub registry"
    command: /etc/buildkite-agent/buildkite-scripts/gh-publish.sh
    timeout_in_minutes: 20
    agents:
      type: aws-buildkite-agent

